---
# ADLabV2 Static Inventory
# IPs are static — Ansible sets them during first-run configuration.

all:
  children:

    linux:
      hosts:
        git01:
          ansible_host: 192.168.100.5

    windows:
      children:

        domain_controllers:
          hosts:
            dc01:
              ansible_host: 192.168.100.10
            dc02:
              ansible_host: 192.168.100.11

        member_servers:
          hosts:
            ca01:
              ansible_host: 192.168.100.20
            db01:
              ansible_host: 192.168.100.30
            web01:
              ansible_host: 192.168.100.40
            vmm01:
              ansible_host: 192.168.100.60

        workstations:
          hosts:
            wks01:
              ansible_host: 192.168.100.50
            wks02:
              ansible_host: 192.168.100.51
